apiVersion: v1
kind: Service
metadata:
  # NOTE: Best practice with a helm chart is to specify namespace using --namespace option
  namespace: "{{ .Release.Namespace }}"
  name: {{ .Release.Name }}-nodeport
spec:
  type: NodePort
  selector:
    app: a-new-startup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
