# Limit Ranges: https://kubernetes.io/docs/concepts/policy/limit-range/
#
# A LimitRange is a policy to constrain the resource allocations (limits and requests) that you can specify for each applicable object kind (such as Pod or PersistentVolumeClaim) in a namespace.
#
# Enforce minimum and maximum compute resources usage per Pod or Container in a namespace.
#
# https://kubernetes.io/docs/concepts/policy/limit-range/
#
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
    defaultRequest: # this section defines default requests
      cpu: 500m
    max: # max and min define the limit range
      cpu: "1"
    min:
      cpu: 100m
    type: Container
