# 
# Create this pod:
# k apply -f setup.yaml 
#
# Check the pod status.
# What's wrong?
# Why is it doing that?
# How can we fix it?
#
apiVersion: v1
kind: Namespace
metadata:
  name: q2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
  namespace: q2
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - 'while true; do echo "Hello"; sleep 5; done'
    env:
    - name: DB_URL
      value: postgresql://mydb:5432
    - name: DB_USERNAME
      value: admin
    image: busybox:1.34.12
    name: test
  dnsPolicy: ClusterFirst
