#
# k apply -f setup.yaml
#
# Check pod status
# How do we fix it?
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: q6
spec:
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-password
  namespace: q6
type: opaque
stringData:
  PASSWORD: mypassword
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: q6
spec:
  containers:
  - image: nginx:1.19.0
    name: app
    # 
    # Mount secret via volume (tmpfs backed)
    #
    volumeMounts:
    - name: secret-volume
      mountPath: /var/app
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: password-secret
