#
#
# k apply -f setup.yaml
#
# Check pod status
# How do we fix it?
#
#
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: q5
spec:
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: q5
spec:
  hard:
    pods: 3
    # NOTE: A ResourceQuota deals in aggregate TOTALS.
    # This number is the TOTAL amount of CPU and MEMORY that can be requested in 
    # the namespace by ALL PODS.  
    requests.cpu: 2000
    requests.memory: 4096
    # This is a MAXIMUM for what all PODS in the NAMESPACE are allowed to use.
    limits.cpu: 6000
    limits.memory: 8192
---
# Will this launch?
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: q5 
spec:
  containers:
  - image: nginx:1.18.0
    name: nginx
    resources:
      requests:
        cpu: 1000
        memory: 512
      limits:
        cpu: 2000
        memory: 1024
