#
#
# By using consistent units, we get the problem sorted out.
# NOTE: You will have to delete the original pod:
# kubectl delete po/pod1 -n q5
#
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: q5
spec:
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: q5
spec:
  hard:
    pods: 3
    # Let's use UNITS consistently so we don't confuse ourselves...
    requests.cpu: 2000m
    requests.memory: 4096Mi
    limits.cpu: 6000m 
    limits.memory: 8192Mi
---
# Will this launch?
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: q5 
spec:
  containers:
  - image: nginx:1.18.0
    name: nginx
    resources:
      requests:
        cpu: 1000m 
        memory: 512Mi
      limits:
        cpu: 2000m 
        memory: 1024Mi
