#
# Chart.yaml - A YAML file containing information about the chart
# Chart.yaml specification: https://helm.sh/docs/topics/charts/#the-chartyaml-file
#
# The chart API version (v1 or v2).  Note that Helm 3 uses chart v2.
apiVersion: v2

# Name of the chart
name: hello-world-amd64
description: A Helm chart for deployment of the Hello World NodeJS application. This version is for AMD64/x86_64

# This is the version of the CHART itself.
# SemVer 2 (Major/Minor/Patch) version.
#  This version number should be incremented each time you make changes
# to the chart and its templates, including the app version. 
version: 1.0.0

# The version of the app being installed. No particular format required, but should be quoted
# to ensure it's handled as a string
# NOTE: This particular chart has image Tag as a variable. That is what really controls the app version to be installed.
# In a production app - you'd have the appVersion here in sync with the Tag of the image you are using.
# (But that's not practical for short quick demos)
#
appVersion: "v1.0.0"

#
# Other stuff of interest... (but not used in this simple example)
#
#
# keywords:
#   - A list of keywords about this project (optional)
# home: The URL of this projects home page (optional)
# sources:
#   - A list of URLs to source code for this project (optional)
# dependencies: # A list of the chart requirements (optional)
#   - name: The name of the chart (nginx)
#     version: The version of the chart ("1.2.3")
#     repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
#     condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
#     tags: # (optional)
#       - Tags can be used to group charts for enabling/disabling together
#     import-values: # (optional)
#       - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
#     alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
# maintainers: # (optional)
#   - name: The maintainers name (required for each maintainer)
#     email: The maintainers email (optional for each maintainer)
#     url: A URL for the maintainer (optional for each maintainer)
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
# appVersion: The version of the app that this contains (optional). Needn't be SemVer. Quotes recommended.
# deprecated: Whether this chart is deprecated (optional, boolean)
# annotations:
#   example: A list of annotations keyed by name (optional).
